from .all_patches import AllPatches
from .base.pooling_base import PoolingBase
from .class_token import ClassToken
from .concat_class_average import ConcatClassAverage
from .identity import Identity
from .index_pooling import IndexPooling
from .max_all import MaxAll
from .max_patch import MaxPatch
from .mean_all import MeanAll
from .mean_patch import MeanPatch
from .to_image import ToImage
